app:
    name: "Sticker Tanks"
    version: 0.9.1
camera:
    number: 0
    debug: False
    rpi_camera: 0
    threaded: True
    resolution: [640,480]
    display: [640,480]
    center_x_offset: 7.0
    center_y_offset: -2.0
    monitor_limit: 1920
    max_monitors: 1
    full_screen: 1
    roi:
        x: [15.0, 90.0]
        y: [5.0, 91.0]
    fps: 20
    src: 0
    brightness: 200
    contrast: 200
    saturation: 230
    sharpness: 230
    exposure: 0
    white_balance: 4200
    awb_mode: "sunlight"
tank:
    check_drain: 1
    mode: "mask"
    filter: "hsv"
    min: [0, 1]
    max: [0, 1]
    size: [[300, 800], [150, 500]]
    area: [10_000,300_000]
    blur: [9,9]
    threshold: 80
    radius: [5, 100, 400]
    min_dist: 250
    params: [450,450]
    canny: [50, 100]
    table_filter: [[42,10,10],[144,255,255]]
sticker:
    threshold: 75
    area:
        min: 300
        max: 5000
    size:
        min: 20
        max: 100
    kernel: [1,1]
    filter: "canny"
    canny: [50,100]
    hsv_filter: [[0, 0, 0], [179, 255, 255]]
    lab_filter: [[70, 115, 100], [255, 145, 140]]
drain:
    arc: 100
    blur: [7, 7]
    kernel: [3, 3]
    area:
        min: 10
        max: 100
    hsv_filter: [[7, 20, 10], [25, 255, 255]]
    lab_filter: [[100, 120, 140], [255, 140, 180]]
plc:
    debug: True
    enabled: 0
    ip: "192.27.6.172"
    rack: 0
    slot: 2
    db_read:
        number: 13
        start: 0
        size: 40
    db_write:
        number: 14
        start: 0
        size: 10
    update_time: 0.2
mask:
    "111": [[140,40], 180]
model:
    sticker:
        size: 70
        channels: 1
        file: "./graphs/graph.h5"
        labels_file: "labels.txt"
        default_labels: ["1","2","P","T","1_180","2_180","P_180","T_180","1_90","2_90","P_90","T_90"]
    drain:
        size: 100
        channels: 1
        file: "./graphs/drain_graph.h5"
        labels_file: "labels.txt"
        default_labels: ["6", "7", "8", "9", "10", "11", "12", "13", "14"]
device:
    ip: '192.27.X.X'
    mac: '00-00-00-00-00-00'
