app:
    name: "Sticker Tanks"
    version: 0.1.0
device:
    number: 0
    type: 1
camera:
    debug: False
    rpi_camera: False
    threaded: True
    resolution: [640,480]
    display: [400, 400]
    monitor_limit: 1920
    max_monitors: 1
    roi: [[6.2, 10], [92, 87]]
    fps: 15
    src: 0
    brighteness: 127
    contrast: 127
    saturation: 127
    sharpness: 127
    exposure: -4
    white_balance: 4200
plc:
    debug: True
    enabled: False
    ip: "192.27.6.172"
    rack: 0
    slot: 2
    db:
        number: 16
        start: 0
        size: 30
    update_time: 0.2
sticker:
    area: [3000, 8000]
    size: [45, 100]
    hsv_filter: [[0, 0, 0], [179, 255, 255]]
    lab_filter: [[200, 115, 100], [255, 145, 140]]
tank:
    prc_min: [0, 1]
    prc_max: [0, 1]
    size: [[700, 250], [500, 1100]]
    area: [0,99999]
    blur: [9,9]
drain:
    blur: [7, 7]
    kernel: [1, 3]
    area: [0, 1]
    hsv_filter: [[7, 20, 10], [25, 255, 255]]
    lab_filter: [[100, 120, 140], [255, 140, 180]]
model:
    size: 70
    channels: 1
    file: "graph.h5"
    labels_file: "labels.txt"
    default_labels: ["1","2","P","T","1_180","2_180","P_180","T_180","1_90","2_90","P_90","T_90"]
