app:
    name: "Sticker Tanks"
    version: 0.1.0
device:
    ip: '192.27.X.X'
    mac: '00-00-00-00-00-00'
camera:
    number: 1
    debug: False
    rpi_camera: 1
    threaded: True
    resolution: [640,480]
    display: [640,480]
    center_x_offset: 7.0
    monitor_limit: 1920
    max_monitors: 1
    roi:
        x: [6.2, 92.0]
        y: [15.0, 85.0]
    fps: 15
    src: 0
    brightness: 200
    contrast: 200
    saturation: 230
    sharpness: 230
    exposure: -4
    white_balance: 4200
plc:
    debug: True
    enabled: False
    ip: "192.27.6.172"
    rack: 0
    slot: 2
    db_read:
        number: 13
        start: 0
        size: 40
    db_write:
        number: 14
        start: 0
        size: 10
    update_time: 0.2
tank:
    min: [0, 1]
    max: [0, 1]
    size: [[300, 800], [150, 500]]
    area: [0,99999]
    blur: [9,9]
    min_radius: 120
    min_dist: 120
    params: [80,80]
    table_filter: [[42,10,10],[144,255,255]]
sticker:
    threshold: 172
    area:
        min: 500
        max: 5000
    size:
        min: 20
        max: 80
    hsv_filter: [[0, 0, 0], [179, 255, 255]]
    lab_filter: [[70, 115, 100], [255, 145, 140]]
drain:
    arc: 100
    blur: [7, 7]
    kernel: [3, 3]
    area:
        min: 10
        max: 100
    hsv_filter: [[7, 20, 10], [25, 255, 255]]
    lab_filter: [[100, 120, 140], [255, 140, 180]]
model:
    sticker:
        size: 70
        channels: 1
        file: "graph.h5"
        labels_file: "labels.txt"
        default_labels: ["1","2","P","T","1_180","2_180","P_180","T_180","1_90","2_90","P_90","T_90"]
    drain:
        size: 100
        channels: 1
        file: "drain_graph.h5"
        labels_file: "labels.txt"
        default_labels: ["6","8", "9", "11", "12","14"]
